name: build

on: 
  pull-request:
    branches:
      - master

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - run: bash qa/check-docstyle.sh 